name: flutter_blue
description: Blue Assistant Flutter version
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.2.0
  flutter_tts: ^3.5.0
  shared_preferences: ^2.0.15
  provider: ^6.0.5
